apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "books-catalog-chart.fullname" . }}
  labels:
    {{- include "books-catalog-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "books-catalog-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port | default 80 }}